#exec tmux

#exec dwm

exec awesome

#plasma
#export DESKTOP_SESSION=plasma
#export KDEWM=/home/jonathan/.local/bin/dwm
#sh /home/jonathan/.kde_dwm.sh
#exec startplasma-x11

#Xfce
#exec startxfce4

#Gnome Xorg
#export XDG_SESSION_TYPE=x11
#export GDK_BACKEND=x11
#exec gnome-session

#Pantheon
#exec wingpanel &
#exec plank &
#exec gala &

#Budgie
#export XDG_CURRENT_DESKTOP=Budgie:GNOME
#exec budgie-desktop
